version: "3.8"

services:
  # Config Server (хранит метаданные кластера)
  mongo-config:
    image: mongo:6.0
    container_name: mongo-config
    command: mongod --configsvr --replSet configrs --port 27019
    ports:
      - "27019:27019"
    volumes:
      - config-data:/data/db

  # Shard 1
  mongo-shard1:
    image: mongo:6.0
    container_name: mongo-shard1
    command: mongod --shardsvr --replSet shard1rs --port 27018
    ports:
      - "27018:27018"
    volumes:
      - shard1-data:/data/db

  # Shard 2
  mongo-shard2:
    image: mongo:6.0
    container_name: mongo-shard2
    command: mongod --shardsvr --replSet shard2rs --port 27017
    ports:
      - "27017:27017"
    volumes:
      - shard2-data:/data/db

  # Mongos Router (точка входа для клиентов)
  mongo-router:
    image: mongo:6.0
    container_name: mongo-router
    command: mongos --configdb configrs/mongo-config:27019 --port 27020 --bind_ip_all
    ports:
      - "27020:27020"
    depends_on:
      - mongo-config
      - mongo-shard1
      - mongo-shard2

volumes:
  config-data:
  shard1-data:
  shard2-data: